name: validate
on: [push, pull_request]
jobs:
  unit-tests:
    timeout-minutes: 60
    runs-on: ["self-hosted", "X64", "ci-tasks"]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: build
        run: |
          ./autogen.sh
          ./configure
          make

      - name: run unit tests
        run: |
          make ci

      - name: Upload test and coverage logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            tests/test-suite.log
            tests/coverage-*.log
